@echo on
@echo Just delete the temporary files generated by Microsoft Visual C++!
del/s *.bak
pause

del/s *.ncb
del/s *.plg
del/s *.aps
del/s *.opt
del/s *.clw
del/s *.suo
pause

del/s *.res
del/s *.obj
del/s *.pdb
del/s *.ilk
del/s *.pch
del/s *.idb
pause